config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  devise_scope :users do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
    get 'register', to: 'devise/registrations#new'
  end

  devise_scope :user do
    post 'users/avatar' => 'users/registrations#avatar', as: :edit_user_avatar
    delete 'users/avatar' => 'users/registrations#destroy_avatar', as: :destroy_user_avatar
    get 'users' => 'users/registrations#list', as: :list_users
  end
  
  resources :posts
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  root 'posts#index'
  
 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, Post
        can :create, Post
        can :update, Post, :user_id => user.id
        can :destroy, Post, :user_id => user.id
      end
    else
      can :read, Post
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  resourcify # for rolify
  validates :title, :body, presence: true
  
  def user
    return User.find(self.user_id)
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  # Roles
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
        :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(updated_at: :desc)
    @tags = @posts.tag_counts_on(:tags).sort { |a, b| a.count <=> b.count }.reverse
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/filter
  def filter
    @posts = Post.tagged_with(params[:tag_name])
    @tags = Post.tag_counts_on(:tags).sort { |a, b| a.count <=> b.count }.reverse
    respond_to do |format|
      format.html { render 'posts/index' }
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:author, :title, :body, :tag_list)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET list
  def list
    if not current_user or not current_user.has_role? :admin
      respond_to do |format|
        format.html { redirect_to :root }
      end
    else
      @users = User.all
    end
  end

  # POST /resource/avatar
  def avatar
    if not current_user
      respond_to do |format|
        format.html { redirect_to :root }
      end
    end
    current_user.avatar = params[:user][:avatar]
    if current_user.save
      respond_to do |format|
        format.html { redirect_to edit_user_registration_url }
      end
    else
      respond_to do |format|
        format.html { redirect_to edit_user_registration_url, alert: 'Failed to update user avatar.' }
      end
    end
  end
  
  def destroy_avatar
    if not current_user
      respond_to do |format|
        format.html { redirect_to :root }
      end
    end
    current_user.avatar = nil
    current_user.save
    respond_to do |format|
      format.html { redirect_to edit_user_registration_url }
    end
  end

  protected

  def user_params
    params.require(:user).permit(:avatar)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
     devise_parameter_sanitizer.for(:sign_in) << :attribute
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Michalův blogísek ¯\_(ツ)_/¯</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="header" class="panel panel-info">
  <div class="panel-heading">
    <div class="panel-title">
      <h1><a href="/">Michalův blogísek ¯\_(ツ)_/¯</a></h1>
    </div>
  </div>
  <div class="panel-footer clearfix">
    <div class="pull-left">
      <% if can? :create, Post %>
        <%= link_to 'New Post', new_post_path, class: 'btn btn-success' %>
      <% end %>
    </div>
    <div class="pull-right">
      <div id="user-panel">
      <% if user_signed_in? %>
        <%= link_to current_user.email, edit_user_registration_path %>&nbsp;&nbsp;&nbsp;
        <% if current_user.has_role? :admin %>
          <%= link_to 'Users', list_users_path, class: 'btn btn-default' %>
        <% end %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'Sign in', new_session_path(:user), class: 'btn btn-primary' %> |
        <%= link_to 'Register', new_registration_path(:user), class: 'btn btn-default' %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<div id="notices">
  <% if notice && !notice.empty? %>
    <div class="alert alert-info" role="alert"><%= notice %></div>
  <% end %>
  <% if alert && !alert.empty? %>
    <div class="alert alert-danger" role="alert"><%= alert %></div>
  <% end %>
</div>

<div id="body">
      
<%= yield %>

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author, id: 'post_author' %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, id: 'post_title' %>
  </div>
  <div class="field">
    <%= f.label :tags_string %><br>
    <%= f.text_field :tag_list, value: @post.tag_list.join(", "), id: 'post_tags_string' %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, id: 'post_body' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class='post panel panel-default' id='post-#<%= post.id %>'>
  <div class='panel-heading'>
    <div class='panel-title'>
      <% if post.user.avatar.file? %>
      <span class="avatar">
        <%= image_tag post.user.avatar.url(:thumb) %>
      </span>
      <% end %>
      <span class="post-title">
        <h1><%= link_to post.title, post_path(post) %></h1><br/>
        by <strong><%= post.user.email %></strong> on <%= post.created_at %>
      </span>
    </div>
  </div>
  <div class='panel-body'>
    <%= simple_format(post.body) %>
  </div>
  <% if can? :update, post %>
  <div class='panel-footer'>
    <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-default' %>
    <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Do you really want to remove post \'' + post.title + '\'?' }, class: 'btn btn-danger' %>
  </div>
  <% end %>
</div>
                                          

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1><a href="/">Posts</a></h1>

<div class="panel panel-default">
  <div class="panel-heading">Tags</div>
  <div class="panel-body">
  <% tag_cloud(@tags, %w(filter-by-tag)) do |tag, css_class| %>
    <%= link_to tag.name, { :action => :filter, :tag_name => tag.name }, :class => css_class %>
  <% end %>
  </div>
</div>

<%= link_to 'New Post', new_post_path, class: 'btn btn-success' %>
<br><br>

<table class="table">
  <tbody>
  <% @posts.each do |post| %>
    <tr id="post-row-<%= post.id %>">
      <td>
        <div class="post-head">
          <span class="post-title"><%= post.title %></span> by <span class="post-author"><%= post.author %></span>
        </div>
        <div class="post-body"><%= post.body %></div>
        <strong>Tags:</strong> <span class="post-tags"><%= post.tag_list %></span>
      </td>
      <td width="150">
        <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-default' %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render @post %>

<%= link_to 'Back', posts_path, class: 'btn btn-default' %>